name: vk_turn_proxy_go_workspace
publish_to: 'none'

environment:
  sdk: ^3.11.4

workspace:
  - desktop/gui_shell
  - mobile/gui_shell
  - packages/flutter_shell_i18n
  - packages/flutter_shell_core

dependency_overrides:
  webview_flutter_android:
    path: third_party/webview_flutter_android
