#!/usr/bin/env python3
import argparse
import json
import pathlib
import re
import sys


def load_manifest(path: pathlib.Path) -> dict[str, str]:
    manifest = json.loads(path.read_text(encoding="utf-8"))
    product = str(manifest.get("product", "")).strip()
    version = str(manifest.get("version", "")).strip()
    build_number = str(manifest.get("build_number", "")).strip()
    if not product:
        raise SystemExit(f"version manifest missing product: {path}")
    if not version:
        raise SystemExit(f"version manifest missing version: {path}")
    if not build_number:
        raise SystemExit(f"version manifest missing build_number: {path}")
    return {
        "product": product,
        "version": version,
        "build_number": build_number,
    }


def sync_pubspec(path: pathlib.Path, expected_version: str, check: bool) -> bool:
    content = path.read_text(encoding="utf-8")
    next_content, count = re.subn(
        r"(?m)^version:\s*[^\r\n]+\s*$",
        f"version: {expected_version}",
        content,
        count=1,
    )
    if count != 1:
        raise SystemExit(f"pubspec version line not found: {path}")
    if next_content == content:
        return False
    if check:
        raise SystemExit(
            f"{path} is out of sync with version.json; expected version {expected_version}"
        )
    path.write_text(next_content, encoding="utf-8")
    return True


def render_dart_defaults(manifest: dict[str, str]) -> str:
    return (
        "// Generated by scripts/sync-version-assets.py. Do not edit by hand.\n"
        "const String kVersionManifestProduct = "
        f"'{manifest['product']}';\n"
        "const String kVersionManifestVersion = "
        f"'{manifest['version']}';\n"
        "const String kVersionManifestBuildNumber = "
        f"'{manifest['build_number']}';\n"
    )


def sync_dart_defaults(path: pathlib.Path, manifest: dict[str, str], check: bool) -> bool:
    expected = render_dart_defaults(manifest)
    current = path.read_text(encoding="utf-8") if path.exists() else ""
    if current == expected:
        return False
    if check:
        raise SystemExit(f"{path} is out of sync with version.json")
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(expected, encoding="utf-8")
    return True


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--repo-root",
        default=pathlib.Path(__file__).resolve().parents[1],
        type=pathlib.Path,
    )
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()

    repo_root = args.repo_root.resolve()
    manifest = load_manifest(repo_root / "version.json")
    expected_version = f"{manifest['version']}+{manifest['build_number']}"

    changed = False
    changed |= sync_pubspec(
        repo_root / "desktop/gui_shell/pubspec.yaml",
        expected_version,
        args.check,
    )
    changed |= sync_dart_defaults(
        repo_root / "desktop/gui_shell/lib/src/build/version_defaults.g.dart",
        manifest,
        args.check,
    )

    if not args.check and changed:
        print("Synchronized Flutter version assets from version.json")
    return 0


if __name__ == "__main__":
    sys.exit(main())
